source 'http://git.hypersmart.cc/hypersmart/platform/ios-group/podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ENetWork_Example' do
  pod 'ENetWork', :path => '../'
  target 'ENetWork_Tests' do
    inherit! :search_paths


    
  end
end
